//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adverts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int AdID { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int CategoryID { get; set; }
        public int CustomerID { get; set; }
    }
}
